import tkinter as tk
window = tk.Tk("Калькулятор времени")
window.geometry("500x500")
window.resizable(False, False)
button_add = tk.Button(window, text="+", windth=2, height=2)
button_add.place(x=100, y=200)
button_sub = tk.Button(window, text="-", windth=2, height=2)
button_sub.place(x=150, y=200)
button_mul = tk.Button(window, text="*", windth=2, height=2)
button_mul.place(x=200, y=200)
button_div = tk.Button(window, text="*", windth=2, height=2)
button_div.place(x=250, y=200)
number1_entry = tk.Entry(window, width=28)
number1_entry.place(x=100, y=200)
number2_entry = tk.Entry(window, width=28)
number2_entry.place(x=100, y=200)